/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
module.exports.seed = async function (knex) {
  await knex("warehouses").del();
  await knex("warehouses").insert([
    {
      id: 1,
      warehouse_name: "Toronto",
      address: "100 Front Street W",
      city: "Toronto",
      country: "Canada",
      contact_name: "Alex Tremblay",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (416) 555-1234",
      contact_email: "atremblay@waresync.ca",
    },
    {
      id: 2,
      warehouse_name: "Vancouver",
      address: "200 Granville Street",
      city: "Vancouver",
      country: "Canada",
      contact_name: "Sophie Chen",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (604) 555-5678",
      contact_email: "schen@waresync.ca",
    },
    {
      id: 3,
      warehouse_name: "Montreal",
      address: "300 Rue Sainte-Catherine O",
      city: "Montreal",
      country: "Canada",
      contact_name: "Jean-Luc Boucher",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (514) 555-7890",
      contact_email: "jboucher@waresync.ca",
    },
    {
      id: 4,
      warehouse_name: "Calgary",
      address: "500 4 Ave SW",
      city: "Calgary",
      country: "Canada",
      contact_name: "Megan O’Donnell",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (403) 555-3456",
      contact_email: "modonnell@waresync.ca",
    },
    {
      id: 5,
      warehouse_name: "Halifax",
      address: "1500 Barrington Street",
      city: "Halifax",
      country: "Canada",
      contact_name: "Connor MacKenzie",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (902) 555-6789",
      contact_email: "cmackenzie@waresync.ca",
    },
    {
      id: 6,
      warehouse_name: "Edmonton",
      address: "10125 109 Street NW",
      city: "Edmonton",
      country: "Canada",
      contact_name: "Natalie Roy",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (780) 555-2345",
      contact_email: "nroy@waresync.ca",
    },
    {
      id: 7,
      warehouse_name: "Winnipeg",
      address: "123 Portage Avenue",
      city: "Winnipeg",
      country: "Canada",
      contact_name: "Brian Kavanagh",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (204) 555-8901",
      contact_email: "bkavanagh@waresync.ca",
    },
    {
      id: 8,
      warehouse_name: "Ottawa",
      address: "50 Elgin Street",
      city: "Ottawa",
      country: "Canada",
      contact_name: "Isabelle Gagnon",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (613) 555-4567",
      contact_email: "igagnon@waresync.ca",
    },
  ]);
};
